export const Users = [
    {
        id:1,
        profilePicture: "assets/person/1.jpeg",
        username: "Jargalsaihan Altangerel",
    },
    {
        id:2,
        profilePicture: "assets/person/2.jpeg",
        username: "John Doe",
    },
    {
        id:3,
        profilePicture: "assets/person/3.jpeg",
        username: "Marin Keis",
    },
    {
        id:4,
        profilePicture: "assets/person/4.jpeg",
        username: "Kalista Rin",
    },
    {
        id:5,
        profilePicture: "assets/person/5.jpeg",
        username: "Sora Rayko",
    },
    {
        id:6,
        profilePicture: "assets/person/6.jpeg",
        username: "Ichigo Kurosaki",
    },
    {
        id:7,
        profilePicture: "assets/person/7.jpeg",
        username: "Safak Naneri",
    },
    {
        id:8,
        profilePicture: "assets/person/8.jpeg",
        username: "Kurokawa Akane",
    },
    {
        id:9,
        profilePicture: "assets/person/9.jpeg",
        username: "Rukia Kuchiki",
    },

    {
        id:10,
        profilePicture: "assets/person/10.jpeg",
        username: "Aizen Sosuke",
    },
];


export const Posts=[
    {
        id : 1,
        desc : "Love for all, hatred for none.",
        photo: "assets/post/1.jpeg",
        date: "5mins ago",
        userId: 1,
        like: 32,
        comment: 9,
    },
    {
        id : 2,
        desc : "Love for all, hatred for none.",
        photo: "assets/post/2.jpeg",
        date: "10mins ago",
        userId: 2,
        like: 2,
        comment: 1,
    },
    {
        id : 3,
        desc : "Love for all, hatred for none.",
        photo: "assets/post/3.jpeg",
        date: "35mins ago",
        userId: 3,
        like: 45,
        comment: 10,
    },
    {
        id : 4,
        desc : "Love for all, hatred for none.",
        photo: "assets/post/4.jpeg",
        date: "40mins ago",
        userId: 4,
        like: 67,
        comment: 7,
    },
    {
        id : 5,
        desc : "Love for all, hatred for none.",
        photo: "assets/post/5.jpeg",
        date: "1hour ago",
        userId: 5,
        like: 88,
        comment: 13,
    },
    {
        id : 6,
        desc : "Love for all, hatred for none.",
        photo: "assets/post/6.jpeg",
        date: "12hours ago",
        userId: 6,
        like: 78,
        comment: 15,
    },
    {
        id : 7,
        desc : "Love for all, hatred for none.",
        photo: "assets/post/7.jpeg",
        date: "18hours ago",
        userId: 7,
        like: 99,
        comment: 3,
    },
    {
        id : 8,
        desc : "Love for all, hatred for none.",
        photo: "assets/post/8.jpeg",
        date: "1day ago",
        userId: 8,
        like: 77,
        comment: 7,
    },
    {
        id : 9,
        desc : "Love for all, hatred for none.",
        photo: "assets/post/9.jpeg",
        date: "2days ago",
        userId: 9,
        like: 88,
        comment: 8,
    },
    {
        id : 10,
        desc : "Love for all, hatred for none.",
        photo: "assets/post/10.jpeg",
        date: "5 days ago",
        userId: 10,
        like: 657,
        comment: 234,
    },

]